language: node_js
node_js:
  - "8"
install:
  - npm install
  - npm install -g nyc codecov
jobs:
  include:
    - stage: Test
      script: npm test
    - stage: Coverage
      script: nyc npm test && nyc report --reporter=text-lcov > coverage.lcov && codecov
